<div class="widget-box">
    <div class="widget-body">
        <div class="widget-main no-padding">
            <form id="termo-form" method="post" class="form-horizontal" >
                <fieldset>
                    <div class="form-group col-sm-12">
                        <label for="nome">Nome:</label>
                        <div>
                            <input type="text" id="nome" class="col-sm-8" placeholder="Nome" required />
                        </div>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="inicio_suporte">Início Suporte:</label>
                        <div>
                            <input type="text" id="inicio_suporte" class="input-sm" />
                        </div>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="fim_suporte">Fim Suporte:</label>
                        <div>
                            <input type="text" id="fim_suporte" class="input-sm" />
                        </div>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="inicio_nucleo">Início Núcleo:</label>
                        <div>
                            <input type="text" id="inicio_nucleo" class="input-sm" />
                        </div>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="fim_nucleo">Fim Núcleo:</label>
                        <div>
                            <input type="text" id="fim_nucleo" class="input-sm" />
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="clearfix form-actions">
            <div class="col-md-offset-3 col-md-9">
                <button id="cadastrar-termo" class="btn btn-success disabled" type="button">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    Cadastrar
                </button>
                &nbsp; &nbsp; &nbsp;
                <button id="cancelar-termo" class="btn btn-danger disabled" type="button">
                    <i class="ace-icon fa fa-times bigger-110"></i>
                    Cancelar
                </button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
  $('#cadastrar-termo').removeClass('disabled');
  $('#cancelar-termo').removeClass('disabled');
  $('#inicio_suporte').ace_spinner({value:0, min:-1000, step:1, btn_up_class:'btn-info' , btn_down_class:'btn-info'});
  $('#fim_suporte').ace_spinner({value:0, min:-1000, step:1, btn_up_class:'btn-info' , btn_down_class:'btn-info'});
  $('#inicio_nucleo').ace_spinner({value:0, min:-1000, step:1, btn_up_class:'btn-info' , btn_down_class:'btn-info'});
  $('#fim_nucleo').ace_spinner({value:0, min:-1000, step:1, btn_up_class:'btn-info' , btn_down_class:'btn-info'});
</script>