<div class="widget-box transparent">
    <div class="widget-header widget-header-flat">
        <h4 class="widget-title lighter">
            <i class="ace-icon fa fa-list green"></i>
            Projetos
        </h4>
    </div>

    <div class="widget-body">
        <div class="widget-main padding-10">
            <div class="row <?php echo count($this->projetos) > 0 ? '' : 'hide'; ?>">
                <table class="table table-striped table-bordered">
                    <thead class="thin-border-bottom">
                        <tr>
                            <th>Nome</th>
                            <th>Descrição</th>
                            <th class="center"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->projetos as $projeto): ?>
                        <tr>
                            <td>
                              <a class="blue" data-rel="tooltip" title="Visualizar" href="projeto/visualizar/id/<?php echo $projeto->id; ?>">
                                  <?php echo $projeto->nome; ?></td>
                              </a>
                            <td><?php echo $projeto->descricao; ?></td>
                            <td class="center">
                                 <a class="blue" data-rel="tooltip" title="Visualizar" href="projeto/visualizar/id/<?php echo $projeto->id; ?>">
                                    <i class="ace-icon fa fa-search-plus bigger-130"></i>
                                </a>
                                <a href="" class="red remover-projeto" data-rel="tooltip" title="Remover">
                                    <input type="hidden" value="<?php echo $projeto->id; ?>" />
                                    <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                </a>
                            </td>
                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </div>
            <div class="row <?php echo count($this->projetos) > 0 ? 'hide' : ''; ?>">
                <h4 class="widget-title grey lighter">
                    <i class="ace-icon fa fa-info"></i>
                    Nenhum projeto adicionado.
                </h4>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
  $('[data-rel=tooltip]').tooltip();
  $("body").removeClass('overflow-scroll');
  $(".carregando").addClass('hide');
</script>