<div class="main-content">
    <div class="main-content-inner">
        <div class="page-content">

            <div class="row">
                <div class="col-xs-12">

                    <div class="space-6"></div>

                    <div class="row">
                        <div class="col-sm-10 col-sm-offset-1">
                            <p>
                                <button class="btn btn-sm btn-success novo-projeto">Novo Projeto</button>
                            </p>
                        </div><!-- /.col -->
                    </div><!-- /.row -->

                    <div class="space-6"></div>

                    <div class="row">
                        <div id="projetos" class="col-sm-10 col-sm-offset-1">
                        </div>
                    </div>

                </div><!-- /.col -->
            </div><!-- /.row -->

        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->