<div class="widget-box">
    <div class="widget-body">
        <div class="widget-main no-padding">
            <form id="projeto-form" method="post" class="form-horizontal" >
                <fieldset>
                    <div class="form-group col-sm-8">
                        <label for="titular">Nome:</label>
                        <div>
                            <input type="text" id="nome" class="col-sm-12" placeholder="Nome" required />
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="descricao">Descrição:</label>
                        <div>
                            <input type="text" id="descricao" class="col-sm-12" placeholder="Descrição" required />
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="clearfix form-actions">
            <div class="col-md-offset-3 col-md-9">
                <button id="cadastrar-projeto" class="btn btn-success disabled" type="button">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    Cadastrar
                </button>
                &nbsp; &nbsp; &nbsp;
                <button id="cancelar-projeto" class="btn btn-danger disabled" type="button">
                    <i class="ace-icon fa fa-times bigger-110"></i>
                    Cancelar
                </button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
  $('#cadastrar-projeto').removeClass('disabled');
  $('#cancelar-projeto').removeClass('disabled');
</script>