<div class="widget-box transparent">
    <div class="widget-header widget-header-flat">
        <h4 class="widget-title lighter">
            <i class="ace-icon fa fa-compass green"></i>
            Simulação
        </h4>
    </div>

    <div class="widget-body">
        <div class="widget-main padding-10">

            <div class="row">
                <?php foreach($this->variaveis as $variavel): ?>
                <div class="col-sm-12">
                    <h4 class="widget-title lighter <?php echo $variavel->objetiva == 1 ? 'red' : 'blue'; ?>">
                        <i class="ace-icon fa <?php echo $variavel->objetiva == 1 ? 'fa-check-circle-o red' : 'fa-circle-o blue'; ?>"></i>
                        <b><?php echo $variavel->nome; ?> (<?php echo $variavel->unidade_medida; ?>): </b> <?php echo $variavel->inicio_universo." a ".$variavel->fim_universo; ?>
                        <?php if($variavel->objetiva != 1): ?>
                        <input type="text" id="valor-<?php echo $variavel->id; ?>" class="input-sm valor-variaveis" />
                        <?php endif; ?>
                    </h4>
                </div><!-- /.col -->
                <script type="text/javascript">
                  $('#valor-<?php echo $variavel->id; ?>').ace_spinner({value:0, min:<?php echo $variavel->inicio_universo; ?>, max:<?php echo $variavel->fim_universo; ?>, step:0.01, btn_up_class:'btn-info' , btn_down_class:'btn-info'});
                </script>
                <?php endforeach;?>
            </div><!-- /.row -->

            <div class="hr hr32 hr-dotted"></div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="widget-box transparent">
                        <div class="widget-header widget-header-flat">
                            <h4 class="widget-title lighter">
                                <i class="ace-icon fa fa-list green"></i>
                                Regras
                            </h4>
                        </div>
                        <div class="widget-body">
                            <div class="widget-main no-padding">
                                <div class="row">
                                    <table class="table table-striped table-bordered">
                                        <tbody>
                                            <?php foreach($this->regras as $regra): ?>
                                            <tr>
                                                <td><?php echo $regra->descricao; ?></td>
                                            </tr>
                                            <?php endforeach;?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- /.col -->
            </div><!-- /.row -->

        </div>
    </div>
</div>

<script type="text/javascript">
  $(".carregando").addClass('hide');
</script>