<div class="widget-box transparent">
    <div class="widget-header widget-header-flat">
        <h4 class="widget-title lighter">
            <i class="ace-icon fa fa-compass green"></i>
            Simulação
        </h4>
    </div>

    <div class="widget-body">
        <div class="widget-main padding-10">

            <div class="row">
                <div class="col-sm-12">
                    <?php foreach($this->variaveis as $variavel): ?>
                        <h4 class="widget-title lighter <?php echo $variavel->objetiva == 1 ? 'red' : 'blue'; ?>">
                            <i class="ace-icon fa <?php echo $variavel->objetiva == 1 ? 'fa-check-circle-o red' : 'fa-circle-o blue'; ?>"></i>
                            <b><?php echo $variavel->nome; ?> (<?php echo $variavel->unidade_medida; ?>): </b> <?php echo $variavel->inicio_universo." a ".$variavel->fim_universo; ?>
                            <?php if($variavel->objetiva != 1): ?>
                                <input type="text" id="valor-<?php echo $variavel->id; ?>" value="<?php echo $variavel->inicio_universo; ?>" class="input-sm valor-variaveis" />
                            <?php else: ?>
                                = <b id="centroide" class="grey">?</b>
                            <?php endif; ?>
                        </h4>
                        <script type="text/javascript">
                          $('#valor-<?php echo $variavel->id; ?>').ace_spinner({value:<?php echo $variavel->inicio_universo; ?>, min:<?php echo $variavel->inicio_universo; ?>, max:<?php echo $variavel->fim_universo; ?>, step:0.01, btn_up_class:'btn-info' , btn_down_class:'btn-info'});
                        </script>
                    <?php endforeach;?>
                </div><!-- /.col -->
            </div><!-- /.row -->

            <div class="hr hr32 hr-dotted"></div>

            <div id="regras-pertinencia" class="row hide">
                <div class="col-sm-8">
                    <div class="widget-box transparent">
                        <div class="widget-header widget-header-flat">
                            <h4 class="widget-title lighter">
                                <i class="ace-icon fa fa-list green"></i>
                                Regras
                            </h4>
                        </div>
                        <div class="widget-body">
                            <div class="widget-main padding-10">
                                <div class="row">
                                    <table id="table-regras-pertinencia" class="table table-striped table-bordered">
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- /.col -->
                <div class="col-sm-4">
                    <div class="widget-box transparent">
                        <div class="widget-header widget-header-flat">
                            <h4 class="widget-title lighter">
                                <i class="ace-icon fa fa-list green"></i>
                                Termos Consequêntes
                            </h4>
                        </div>
                        <div class="widget-body">
                            <div class="widget-main padding-10">
                                <div class="row">
                                    <table id="table-termos-consequentes" class="table table-striped table-bordered">
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- /.col -->
            </div><!-- /.row -->
            <div class="row">
                <div class="col-sm-12">
                    <?php foreach($this->variaveis as $variavel): ?>
                        <?php if($variavel->objetiva == 1): ?>
                            <div id="<?php echo $variavel->id; ?>" class="grafico-variavel-objetiva grafico-variavel-objetiva-<?php echo $variavel->id; ?>"></div>
                        <?php endif; ?>
                    <?php endforeach;?>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div>
    </div>
</div>

<script type="text/javascript">
  $(".carregando").addClass('hide');
</script>