<div class="main-content">
    <div class="main-content-inner">
        <!-- #section:basics/content.breadcrumbs -->
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
            </script>

            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="<?php echo $this->baseUrl("/"); ?>">Página Inicial</a>
                </li>
                <li class="active"><?php echo $this->message ?></li>
            </ul><!-- /.breadcrumb -->
        </div>

        <div class="page-content">
            <div class="row">
                <div class="col-xs-12">
                <!-- PAGE CONTENT BEGINS -->

                    <!-- #section:pages/error -->
                    <div class="error-container">
                        <div class="well">
                            <h1 class="grey lighter smaller">
                                <span class="blue bigger-125">
                                    <i class="ace-icon fa fa-sitemap"></i>
                                    404
                                </span>
                                <?php echo $this->message ?>
                            </h1>
                            <hr />
                            <h3 class="lighter smaller">Não foi possível encontrar a página que você estava procurando.</h3>
                            <hr />
                            <?php if (isset($this->exception)): ?>
                                <div class="space"></div>
                                <h3>Exception information:</h3>
                                <p>
                                    <b>Message:</b> <?php echo $this->exception->getMessage() ?>
                                </p>

                                <h3>Stack trace:</h3>
                                <pre><?php echo $this->exception->getTraceAsString() ?></pre>

                                <h3>Request Parameters:</h3>
                                <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
                                <hr />
                            <?php endif ?>
                            <div class="space"></div>
                            <div class="center">
                                <a href="javascript:history.back()" class="btn btn-grey">
                                    <i class="ace-icon fa fa-arrow-left"></i>
                                    Voltar
                                </a>

                                <a href="<?php echo $this->baseUrl("/"); ?>" class="btn btn-primary">
                                    <i class="ace-icon fa fa-tachometer"></i>
                                    Página Inicial
                                </a>
                            </div>
                        </div>
                    </div>
                    <!-- /section:pages/error -->
                <!-- PAGE CONTENT ENDS -->
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->