<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <base href="<?php echo $this->baseUrl("/"); ?>" />
        <link href="<?php echo $this->baseUrl("assets/images/favicon.ico"); ?>" rel="shortcut icon" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <!-- bootstrap & fontawesome -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl("assets/css/bootstrap.css"); ?>" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl("assets/css/font-awesome.css"); ?>" />
        <!-- page specific plugin styles -->
        <?php echo $this->headLink() ?>
        <!-- text fonts -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl("assets/css/ace-fonts.css"); ?>" />
        <!-- ace styles -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl("assets/css/ace.css"); ?>" class="ace-main-stylesheet" id="main-ace-style" />
        <!--[if lte IE 9]>
        <link rel="stylesheet" href="<?php echo $this->baseUrl("assets/css/ace-part2.css"); ?>" class="ace-main-stylesheet" />
        <![endif]-->
        <!--[if lte IE 9]>
        <link rel="stylesheet" href="<?php echo $this->baseUrl("assets/css/ace-ie.css"); ?>" />
        <![endif]-->
        <!-- ace settings handler -->
        <script src="<?php echo $this->baseUrl("assets/js/ace-extra.js"); ?>"></script>
        <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->
        <!--[if lte IE 8]>
        <script src="<?php echo $this->baseUrl("assets/js/html5shiv.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("assets/js/respond.js"); ?>"></script>
        <![endif]-->
    </head>
    <body class="no-skin">

        <div id="navbar" class="navbar navbar-default">
            <script type="text/javascript">
                try{ace.settings.check('navbar' , 'fixed')}catch(e){}
            </script>

            <div class="navbar-container" id="navbar-container">
                <div class="navbar-header pull-left">
                    <a href="<?php echo $this->baseUrl("/"); ?>" class="navbar-brand">
                        <small>
                            <img src="<?php echo $this->baseUrl("assets/images/logo.png"); ?>" />
                            Sistemas Difusos
                        </small>
                    </a>
                </div>

                <div class="navbar-header pull-right">
                    <a href="https://github.com/RodrigoSyprianoRibeiro/sistemas-difusos" target="_blank" class="navbar-brand">
                        <small>
                            <i class="fa fa-github"></i> GitHub
                        </small>
                    </a>
                </div>
            </div><!-- /.navbar-container -->
        </div>

        <div class="main-container" id="main-container">
            <script type="text/javascript">
                try{ace.settings.check('main-container' , 'fixed')}catch(e){}
            </script>

            <div class="main-content">
                <div class="main-content-inner">

                    <?php echo $this->Layout()->content; ?>

                    <div class="page-content">
                        <div class="row center">
                            <div class="col-xs-12">
                                <div class="clearfix form-actions">
                                    <a href="http://php.net/" target="_blank">
                                        <img src="<?php echo $this->baseUrl("assets/images/php.png"); ?>" />
                                    </a>
                                    <a href="http://framework.zend.com/" target="_blank">
                                        <img src="<?php echo $this->baseUrl("assets/images/zf.png"); ?>" />
                                    </a>
                                    <a href="https://jquery.com/" target="_blank">
                                        <img src="<?php echo $this->baseUrl("assets/images/jquery.png"); ?>" />
                                    </a>
                                    <a href="https://www.mysql.com/" target="_blank">
                                        <img src="<?php echo $this->baseUrl("assets/images/mysql.png"); ?>" />
                                    </a>
                                    <a href="https://github.com/" target="_blank">
                                        <img src="<?php echo $this->baseUrl("assets/images/github.png"); ?>" />
                                    </a>
                                    <a href="https://www.digitalocean.com/" target="_blank">
                                        <img src="<?php echo $this->baseUrl("assets/images/digital_ocean.png"); ?>" />
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.page-content -->

                </div>
            </div><!-- /.main-content -->

            <div class="widget-box-overlay carregando">
                <i class=" ace-icon loading-icon fa fa-spinner fa-spin fa-2x white"></i>
            </div>

            <div class="footer">
                <div class="footer-inner">
                    <div class="footer-content">
                        <span class="bigger-120">
                            <span class="blue bolder">
                                <a href="http://sistemasdifusos.tk/" target="_blank" >Sistemas Difusos</a>
                            </span>
                            &copy; 2016
                        </span>
                    </div>
                </div>
            </div>

            <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
                <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
            </a>
        </div><!-- /.main-container -->

        <script type="text/javascript">
            var BASEURL = "<?php echo $this->baseUrl("/"); ?>";
        </script>
        <!-- basic scripts -->
        <!--[if !IE]> -->
        <script type="text/javascript">
            window.jQuery || document.write("<script src='<?php echo $this->baseUrl("assets/js/jquery.js"); ?>'>"+"<"+"/script>");
        </script>
        <!-- <![endif]-->
        <!--[if IE]>
        <script type="text/javascript">
            window.jQuery || document.write("<script src='<?php echo $this->baseUrl("assets/js/jquery1x.js"); ?>'>"+"<"+"/script>");
        </script>
        <![endif]-->
        <script type="text/javascript">
            if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo $this->baseUrl("assets/js/jquery.mobile.custom.js"); ?>'>"+"<"+"/script>");
        </script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/bootstrap.js"); ?>"></script>
        <!-- page specific plugin scripts -->
        <?php echo $this->inlineScript() ?>
        <!-- ace scripts -->
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/elements.scroller.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/elements.colorpicker.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/elements.fileinput.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/elements.typeahead.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/elements.wysiwyg.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/elements.spinner.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/elements.treeview.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/elements.wizard.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/elements.aside.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.ajax-content.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.touch-drag.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.sidebar.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.sidebar-scroll-1.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.submenu-hover.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.widget-box.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.settings.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.settings-rtl.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.settings-skin.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.widget-on-reload.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets/js/ace/ace.searchbox-autocomplete.js"); ?>"></script>
    </body>
</html>