<div class="widget-box">
    <div class="widget-header widget-header-flat">
        <h4 class="widget-title lighter blue">
            <i class="ace-icon fa fa-graduation-cap green"></i>
            <b><?php echo $this->projeto->nome; ?></b>
        </h4>
    </div>
    <div class="widget-body">
        <div class="widget-main no-padding">
            <form id="variavel-form" method="post" class="form-horizontal" >
                <fieldset>
                    <div class="form-group col-sm-12">
                        <label for="nome">Nome:</label>
                        <div>
                            <input type="text" id="nome" class="col-sm-8" placeholder="Nome" required />
                        </div>
                        <div class="col-sm-4">
                            <input type="checkbox" id="objetiva" class="ace" />
                            <span class="lbl"> Objetiva</span>
                        </div>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="inicio_universo">Início Universo:</label>
                        <div>
                            <input type="text" id="inicio_universo" class="input-sm" />
                        </div>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="fim_universo">Fim Universo:</label>
                        <div>
                            <input type="text" id="fim_universo" class="input-sm" />
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="unidade_medida">Unidade Medida:</label>
                        <div>
                            <select id="id_unidade_medida" data-placeholder="Unidade Medida" required >
                                <option value=""></option>
                                <?php foreach($this->unidades_medidas as $unidade_medida): ?>
                                <option value="<?php echo $unidade_medida->id; ?>"><?php echo $unidade_medida->nome." (".$unidade_medida->sigla.")"; ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="clearfix form-actions">
            <div class="col-md-offset-3 col-md-9">
                <button id="cadastrar-variavel" class="btn btn-success disabled" type="button">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    Cadastrar
                </button>
                &nbsp; &nbsp; &nbsp;
                <button id="cancelar-variavel" class="btn btn-danger disabled" type="button">
                    <i class="ace-icon fa fa-times bigger-110"></i>
                    Cancelar
                </button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
  $('#cadastrar-variavel').removeClass('disabled');
  $('#cancelar-variavel').removeClass('disabled');
  $('#inicio_universo').ace_spinner({value:0, min:-10000, max:10000, step:1, btn_up_class:'btn-info' , btn_down_class:'btn-info'});
  $('#fim_universo').ace_spinner({value:0, min:-10000, max:10000, step:1, btn_up_class:'btn-info' , btn_down_class:'btn-info'});
  $("#id_unidade_medida").css('width','100%').select2({allowClear:true});
</script>