<div class="widget-box">
    <div class="widget-body">
        <div class="widget-main no-padding">
            <form id="variavel-form" method="post" class="form-horizontal" >
                <fieldset>
                    <div class="form-group col-sm-12">
                        <label for="nome">Nome:</label>
                        <div>
                            <input type="text" id="nome" class="col-sm-8" placeholder="Nome" required />
                        </div>
                        <div class="col-sm-4">
                            <input type="checkbox" id="objetiva" class="ace" />
                            <span class="lbl"> Objetiva</span>
                        </div>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="inicio_universo">Início Universo:</label>
                        <div>
                            <input type="text" id="inicio_universo" class="input-sm" />
                        </div>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="fim_universo">Fim Universo:</label>
                        <div>
                            <input type="text" id="fim_universo" class="input-sm" />
                        </div>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="unidade_medida">Unidade Medida:</label>
                        <div>
                            <select id="unidade_medida" data-placeholder="Unidade Medida" required >
                                <option value=""></option>
                                <option value="CM">Centímetro (CM)</option>
                                <option value="M">Metro (M)</option>
                                <option value="KM">Quilômetro (KM)</option>
                                <option value="KM/H">Quilômetro por Hora (KM/H)</option>
                                <option value="CM²">Centímetro Quadrado (CM²)</option>
                                <option value="M²">Metro Quadrado (M²)</option>
                                <option value="CM³">Centímetro Cúbico (CM³)</option>
                                <option value="M³">Metro Cúbico (M³)</option>
                                <option value="L">Litro (L)</option>
                                <option value="KG">Quilograma (KG)</option>
                                <option value="T">Tonelada (T)</option>
                                <option value="Hz">Hertz (Hz)</option>
                                <option value="W">Whatt (W)</option>
                                <option value="A">Ampére (A)</option>
                                <option value="V">Volt (V)</option>
                                <option value="N">Newton (N)</option>
                                <option value="H">Hora (H)</option>
                                <option value="Min">Minuto (Min)</option>
                                <option value="S">Segundo (S)</option>
                                <option value="Cº">Celsius (Cº)</option>
                                <option value="º">Ângulo (º)</option>
                                <option value="%">Porcentagem (%)</option>
                            </select>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="clearfix form-actions">
            <div class="col-md-offset-3 col-md-9">
                <button id="cadastrar-variavel" class="btn btn-success disabled" type="button">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    Cadastrar
                </button>
                &nbsp; &nbsp; &nbsp;
                <button id="cancelar-variavel" class="btn btn-danger disabled" type="button">
                    <i class="ace-icon fa fa-times bigger-110"></i>
                    Cancelar
                </button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
  $('#cadastrar-variavel').removeClass('disabled');
  $('#cancelar-variavel').removeClass('disabled');
  $('#inicio_universo').ace_spinner({value:0, min:-1000, step:1, btn_up_class:'btn-info' , btn_down_class:'btn-info'});
  $('#fim_universo').ace_spinner({value:0, min:-1000, step:1, btn_up_class:'btn-info' , btn_down_class:'btn-info'});
  $("#unidade_medida").css('width','100%').select2({allowClear:true});
</script>